# Auto-generated from datasets-manifest.json
# Maps schema.table -> {provider, source_url, api_url, dataset_id}
SOURCE_REGISTRY: dict[str, dict] = {
    "business.acris_pp_parties": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/nbbg-wtuz", "api_url": "https://data.cityofnewyork.us/resource/nbbg-wtuz.json", "dataset_id": "nbbg-wtuz"},
    "business.bic_denied_companies": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/exsg-kpya", "api_url": "https://data.cityofnewyork.us/resource/exsg-kpya.json", "dataset_id": "exsg-kpya"},
    "business.bic_trade_waste": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/867j-5pgi", "api_url": "https://data.cityofnewyork.us/resource/867j-5pgi.json", "dataset_id": "867j-5pgi"},
    "business.bic_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/upii-frjc", "api_url": "https://data.cityofnewyork.us/resource/upii-frjc.json", "dataset_id": "upii-frjc"},
    "business.bic_wholesale_markets": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/87fx-28ei", "api_url": "https://data.cityofnewyork.us/resource/87fx-28ei.json", "dataset_id": "87fx-28ei"},
    "business.dcwp_charges": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5fn4-dr26", "api_url": "https://data.cityofnewyork.us/resource/5fn4-dr26.json", "dataset_id": "5fn4-dr26"},
    "business.issued_licenses": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/w7w3-xahh", "api_url": "https://data.cityofnewyork.us/resource/w7w3-xahh.json", "dataset_id": "w7w3-xahh"},
    "business.license_applications": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ptev-4hud", "api_url": "https://data.cityofnewyork.us/resource/ptev-4hud.json", "dataset_id": "ptev-4hud"},
    "business.nys_contractor_registry": {"provider": "socrata", "source_url": "https://data.ny.gov/d/i4jv-zkey", "api_url": "https://data.ny.gov/resource/i4jv-zkey.json", "dataset_id": "i4jv-zkey"},
    "business.nys_corp_all_filings": {"provider": "socrata", "source_url": "https://data.ny.gov/d/63wc-4exh", "api_url": "https://data.ny.gov/resource/63wc-4exh.json", "dataset_id": "63wc-4exh"},
    "business.nys_corp_constituents": {"provider": "socrata", "source_url": "https://data.ny.gov/d/dnbf-xifz", "api_url": "https://data.ny.gov/resource/dnbf-xifz.json", "dataset_id": "dnbf-xifz"},
    "business.nys_corp_name_history": {"provider": "socrata", "source_url": "https://data.ny.gov/d/ekwr-p59j", "api_url": "https://data.ny.gov/resource/ekwr-p59j.json", "dataset_id": "ekwr-p59j"},
    "business.nys_corporations": {"provider": "socrata", "source_url": "https://data.ny.gov/d/n9v6-gdp6", "api_url": "https://data.ny.gov/resource/n9v6-gdp6.json", "dataset_id": "n9v6-gdp6"},
    "business.nys_daily_corp_filings": {"provider": "socrata", "source_url": "https://data.ny.gov/d/k4vb-judh", "api_url": "https://data.ny.gov/resource/k4vb-judh.json", "dataset_id": "k4vb-judh"},
    "business.nys_dos_nonprofits": {"provider": "socrata", "source_url": "https://data.ny.gov/d/s9yk-pe33", "api_url": "https://data.ny.gov/resource/s9yk-pe33.json", "dataset_id": "s9yk-pe33"},
    "business.nys_entity_addresses": {"provider": "socrata", "source_url": "https://data.ny.gov/d/2tms-hftb", "api_url": "https://data.ny.gov/resource/2tms-hftb.json", "dataset_id": "2tms-hftb"},
    "business.nys_liquor_authority": {"provider": "socrata", "source_url": "https://data.ny.gov/d/9s3h-dpkz", "api_url": "https://data.ny.gov/resource/9s3h-dpkz.json", "dataset_id": "9s3h-dpkz"},
    "business.nys_non_responsible": {"provider": "socrata", "source_url": "https://data.ny.gov/d/jhxt-dfv6", "api_url": "https://data.ny.gov/resource/jhxt-dfv6.json", "dataset_id": "jhxt-dfv6"},
    "business.sbs_certified": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ci93-uc8s", "api_url": "https://data.cityofnewyork.us/resource/ci93-uc8s.json", "dataset_id": "ci93-uc8s"},
    "business.sidewalk_cafe": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qcdj-rwhu", "api_url": "https://data.cityofnewyork.us/resource/qcdj-rwhu.json", "dataset_id": "qcdj-rwhu"},
    "business.sustainability_compliance": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/355w-xvp2", "api_url": "https://data.cityofnewyork.us/resource/355w-xvp2.json", "dataset_id": "355w-xvp2"},
    "city_government.birth_certificates_1855_1909": {"provider": "static"},
    "city_government.campaign_contributions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/rjkp-yttg", "api_url": "https://data.cityofnewyork.us/resource/rjkp-yttg.json", "dataset_id": "rjkp-yttg"},
    "city_government.campaign_expenditures": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qxzj-vkn2", "api_url": "https://data.cityofnewyork.us/resource/qxzj-vkn2.json", "dataset_id": "qxzj-vkn2"},
    "city_government.cfb_enforcement_audits": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/x4w5-m7uh", "api_url": "https://data.cityofnewyork.us/resource/x4w5-m7uh.json", "dataset_id": "x4w5-m7uh"},
    "city_government.cfb_enforcement_penalties": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xrxs-qn95", "api_url": "https://data.cityofnewyork.us/resource/xrxs-qn95.json", "dataset_id": "xrxs-qn95"},
    "city_government.cfb_intermediaries": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tcwb-nry3", "api_url": "https://data.cityofnewyork.us/resource/tcwb-nry3.json", "dataset_id": "tcwb-nry3"},
    "city_government.cfb_offyear_contributions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/kgzj-pjna", "api_url": "https://data.cityofnewyork.us/resource/kgzj-pjna.json", "dataset_id": "kgzj-pjna"},
    "city_government.city_record": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dg92-zbpx", "api_url": "https://data.cityofnewyork.us/resource/dg92-zbpx.json", "dataset_id": "dg92-zbpx"},
    "city_government.citywide_payroll": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/k397-673e", "api_url": "https://data.cityofnewyork.us/resource/k397-673e.json", "dataset_id": "k397-673e"},
    "city_government.civil_list": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ye3c-m4ga", "api_url": "https://data.cityofnewyork.us/resource/ye3c-m4ga.json", "dataset_id": "ye3c-m4ga"},
    "city_government.civil_litigation": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/pjgc-h7uv", "api_url": "https://data.cityofnewyork.us/resource/pjgc-h7uv.json", "dataset_id": "pjgc-h7uv"},
    "city_government.civil_service_active": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/vx8i-nprf", "api_url": "https://data.cityofnewyork.us/resource/vx8i-nprf.json", "dataset_id": "vx8i-nprf"},
    "city_government.civil_service_titles": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/nzjr-3966", "api_url": "https://data.cityofnewyork.us/resource/nzjr-3966.json", "dataset_id": "nzjr-3966"},
    "city_government.coib_agency_donations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/aqs7-v55z", "api_url": "https://data.cityofnewyork.us/resource/aqs7-v55z.json", "dataset_id": "aqs7-v55z"},
    "city_government.coib_elected_nfp_donations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dx8z-6nev", "api_url": "https://data.cityofnewyork.us/resource/dx8z-6nev.json", "dataset_id": "dx8z-6nev"},
    "city_government.coib_enforcement": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/p39r-nm7f", "api_url": "https://data.cityofnewyork.us/resource/p39r-nm7f.json", "dataset_id": "p39r-nm7f"},
    "city_government.coib_legal_defense_trust": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/jsiv-zh9r", "api_url": "https://data.cityofnewyork.us/resource/jsiv-zh9r.json", "dataset_id": "jsiv-zh9r"},
    "city_government.coib_official_fundraising": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/basd-2jwn", "api_url": "https://data.cityofnewyork.us/resource/basd-2jwn.json", "dataset_id": "basd-2jwn"},
    "city_government.coib_policymakers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/wf8t-6cqt", "api_url": "https://data.cityofnewyork.us/resource/wf8t-6cqt.json", "dataset_id": "wf8t-6cqt"},
    "city_government.contract_awards": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qyyg-4tf5", "api_url": "https://data.cityofnewyork.us/resource/qyyg-4tf5.json", "dataset_id": "qyyg-4tf5"},
    "city_government.covid_emergency_contracts": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5w2t-dbac", "api_url": "https://data.cityofnewyork.us/resource/5w2t-dbac.json", "dataset_id": "5w2t-dbac"},
    "city_government.ddc_vendor_payments": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/rb9h-9fit", "api_url": "https://data.cityofnewyork.us/resource/rb9h-9fit.json", "dataset_id": "rb9h-9fit"},
    "city_government.death_certificates_1862_1948": {"provider": "static"},
    "city_government.doing_business_contributions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/fbkk-n4e3", "api_url": "https://data.cityofnewyork.us/resource/fbkk-n4e3.json", "dataset_id": "fbkk-n4e3"},
    "city_government.doing_business_entities": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/72mk-a8z7", "api_url": "https://data.cityofnewyork.us/resource/72mk-a8z7.json", "dataset_id": "72mk-a8z7"},
    "city_government.doing_business_people": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/2sps-j9st", "api_url": "https://data.cityofnewyork.us/resource/2sps-j9st.json", "dataset_id": "2sps-j9st"},
    "city_government.elobbyist": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/fmf3-knd8", "api_url": "https://data.cityofnewyork.us/resource/fmf3-knd8.json", "dataset_id": "fmf3-knd8"},
    "city_government.film_permits": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tg4x-b46p", "api_url": "https://data.cityofnewyork.us/resource/tg4x-b46p.json", "dataset_id": "tg4x-b46p"},
    "city_government.laus": {"provider": "socrata", "source_url": "https://data.ny.gov/d/5hyu-bdh8", "api_url": "https://data.ny.gov/resource/5hyu-bdh8.json", "dataset_id": "5hyu-bdh8"},
    "city_government.lobbyist_fundraising": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/7arw-dbem", "api_url": "https://data.cityofnewyork.us/resource/7arw-dbem.json", "dataset_id": "7arw-dbem"},
    "city_government.marriage_certificates_1866_1937": {"provider": "static"},
    "city_government.marriage_licenses_1908_1949": {"provider": "static"},
    "city_government.marriage_licenses_1950_2017": {"provider": "static", "source_url": "https://www.nyc.gov/site/records/about/municipal-archives.page"},
    "city_government.nyc_jobs": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/kpav-sd4t", "api_url": "https://data.cityofnewyork.us/resource/kpav-sd4t.json", "dataset_id": "kpav-sd4t"},
    "city_government.nys_campaign_contributions": {"provider": "socrata", "source_url": "https://data.ny.gov/d/4j2b-6a2j", "api_url": "https://data.ny.gov/resource/4j2b-6a2j.json", "dataset_id": "4j2b-6a2j"},
    "city_government.nys_campaign_expenditures": {"provider": "socrata", "source_url": "https://data.ny.gov/d/ajsb-8pni", "api_url": "https://data.ny.gov/resource/ajsb-8pni.json", "dataset_id": "ajsb-8pni"},
    "city_government.nys_campaign_filer_ref": {"provider": "socrata", "source_url": "https://data.ny.gov/d/7x2g-h32p", "api_url": "https://data.ny.gov/resource/7x2g-h32p.json", "dataset_id": "7x2g-h32p"},
    "city_government.nys_campaign_finance": {"provider": "socrata", "source_url": "https://data.ny.gov/d/e9ss-239a", "api_url": "https://data.ny.gov/resource/e9ss-239a.json", "dataset_id": "e9ss-239a"},
    "city_government.nys_coelig_enforcement": {"provider": "socrata", "source_url": "https://data.ny.gov/d/vsmx-hgi8", "api_url": "https://data.ny.gov/resource/vsmx-hgi8.json", "dataset_id": "vsmx-hgi8"},
    "city_government.nys_lobbyist_disclosures_pre2019": {"provider": "socrata", "source_url": "https://data.ny.gov/d/djsm-9cw7", "api_url": "https://data.ny.gov/resource/djsm-9cw7.json", "dataset_id": "djsm-9cw7"},
    "city_government.nys_lobbyist_public_monies": {"provider": "socrata", "source_url": "https://data.ny.gov/d/scx8-uayk", "api_url": "https://data.ny.gov/resource/scx8-uayk.json", "dataset_id": "scx8-uayk"},
    "city_government.nys_lobbyist_registration": {"provider": "socrata", "source_url": "https://data.ny.gov/d/se5j-cmbb", "api_url": "https://data.ny.gov/resource/se5j-cmbb.json", "dataset_id": "se5j-cmbb"},
    "city_government.oath_hearings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/jz4z-kudi", "api_url": "https://data.cityofnewyork.us/resource/jz4z-kudi.json", "dataset_id": "jz4z-kudi"},
    "city_government.oath_trials": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/y3hw-z6bm", "api_url": "https://data.cityofnewyork.us/resource/y3hw-z6bm.json", "dataset_id": "y3hw-z6bm"},
    "city_government.occupational_projections": {"provider": "socrata", "source_url": "https://data.ny.gov/d/pqm4-9qqb", "api_url": "https://data.ny.gov/resource/pqm4-9qqb.json", "dataset_id": "pqm4-9qqb"},
    "city_government.oews": {"provider": "socrata", "source_url": "https://data.ny.gov/d/gkgz-nw24", "api_url": "https://data.ny.gov/resource/gkgz-nw24.json", "dataset_id": "gkgz-nw24"},
    "city_government.passport_vendors": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/irs3-wn2g", "api_url": "https://data.cityofnewyork.us/resource/irs3-wn2g.json", "dataset_id": "irs3-wn2g"},
    "city_government.permitted_events": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tvpp-9vvx", "api_url": "https://data.cityofnewyork.us/resource/tvpp-9vvx.json", "dataset_id": "tvpp-9vvx"},
    "city_government.pluto": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/64uk-42ks", "api_url": "https://data.cityofnewyork.us/resource/64uk-42ks.json", "dataset_id": "64uk-42ks"},
    "city_government.qcew_annual": {"provider": "socrata", "source_url": "https://data.ny.gov/d/shc7-xcbw", "api_url": "https://data.ny.gov/resource/shc7-xcbw.json", "dataset_id": "shc7-xcbw"},
    "city_government.revenue_budget": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ugzk-a6x4", "api_url": "https://data.cityofnewyork.us/resource/ugzk-a6x4.json", "dataset_id": "ugzk-a6x4"},
    "city_government.settlement_payments": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/d7pv-3qwq", "api_url": "https://data.cityofnewyork.us/resource/d7pv-3qwq.json", "dataset_id": "d7pv-3qwq"},
    "education.attendance_2015": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/3y5p-x48f", "api_url": "https://data.cityofnewyork.us/resource/3y5p-x48f.json", "dataset_id": "3y5p-x48f"},
    "education.attendance_2018": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xc44-2jrh", "api_url": "https://data.cityofnewyork.us/resource/xc44-2jrh.json", "dataset_id": "xc44-2jrh"},
    "education.capacity_projects": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/a94k-kjys", "api_url": "https://data.cityofnewyork.us/resource/a94k-kjys.json", "dataset_id": "a94k-kjys"},
    "education.chronic_absenteeism": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/gqq2-hgxd", "api_url": "https://data.cityofnewyork.us/resource/gqq2-hgxd.json", "dataset_id": "gqq2-hgxd"},
    "education.class_size": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/sgr7-hhwp", "api_url": "https://data.cityofnewyork.us/resource/sgr7-hhwp.json", "dataset_id": "sgr7-hhwp"},
    "education.demographics_2013": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/s52a-8aq6", "api_url": "https://data.cityofnewyork.us/resource/s52a-8aq6.json", "dataset_id": "s52a-8aq6"},
    "education.demographics_2018": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/45j8-f6um", "api_url": "https://data.cityofnewyork.us/resource/45j8-f6um.json", "dataset_id": "45j8-f6um"},
    "education.demographics_2019": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/nie4-bv6q", "api_url": "https://data.cityofnewyork.us/resource/nie4-bv6q.json", "dataset_id": "nie4-bv6q"},
    "education.demographics_2020": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/vmmu-wj3w", "api_url": "https://data.cityofnewyork.us/resource/vmmu-wj3w.json", "dataset_id": "vmmu-wj3w"},
    "education.discharge_reporting": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/a2gn-nyzs", "api_url": "https://data.cityofnewyork.us/resource/a2gn-nyzs.json", "dataset_id": "a2gn-nyzs"},
    "education.ela_results": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/iebs-5yhr", "api_url": "https://data.cityofnewyork.us/resource/iebs-5yhr.json", "dataset_id": "iebs-5yhr"},
    "education.math_results": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/74kb-55u9", "api_url": "https://data.cityofnewyork.us/resource/74kb-55u9.json", "dataset_id": "74kb-55u9"},
    "education.quality_early_childhood": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/kkng-ugna", "api_url": "https://data.cityofnewyork.us/resource/kkng-ugna.json", "dataset_id": "kkng-ugna"},
    "education.quality_elem_middle": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/jtpv-nuuc", "api_url": "https://data.cityofnewyork.us/resource/jtpv-nuuc.json", "dataset_id": "jtpv-nuuc"},
    "education.quality_high_schools": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ci36-d7ea", "api_url": "https://data.cityofnewyork.us/resource/ci36-d7ea.json", "dataset_id": "ci36-d7ea"},
    "education.quality_reports": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dnpx-dfnc", "api_url": "https://data.cityofnewyork.us/resource/dnpx-dfnc.json", "dataset_id": "dnpx-dfnc"},
    "education.regents_results": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bnea-fu3k", "api_url": "https://data.cityofnewyork.us/resource/bnea-fu3k.json", "dataset_id": "bnea-fu3k"},
    "education.school_programs": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/esmb-8zkm", "api_url": "https://data.cityofnewyork.us/resource/esmb-8zkm.json", "dataset_id": "esmb-8zkm"},
    "education.school_safety": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qybk-bjjc", "api_url": "https://data.cityofnewyork.us/resource/qybk-bjjc.json", "dataset_id": "qybk-bjjc"},
    "education.specialized_hs_summary": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/unse-x4pq", "api_url": "https://data.cityofnewyork.us/resource/unse-x4pq.json", "dataset_id": "unse-x4pq"},
    "education.specialized_hs_tests": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/k8ah-28f4", "api_url": "https://data.cityofnewyork.us/resource/k8ah-28f4.json", "dataset_id": "k8ah-28f4"},
    "education.survey_parents": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4fcz-jias", "api_url": "https://data.cityofnewyork.us/resource/4fcz-jias.json", "dataset_id": "4fcz-jias"},
    "education.survey_students": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/k2zg-756q", "api_url": "https://data.cityofnewyork.us/resource/k2zg-756q.json", "dataset_id": "k2zg-756q"},
    "education.survey_teachers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/uzmq-2khh", "api_url": "https://data.cityofnewyork.us/resource/uzmq-2khh.json", "dataset_id": "uzmq-2khh"},
    "environment.air_quality": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/c3uy-2p5r", "api_url": "https://data.cityofnewyork.us/resource/c3uy-2p5r.json", "dataset_id": "c3uy-2p5r"},
    "environment.asthma_ed": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ebe7-6eah", "api_url": "https://data.cityofnewyork.us/resource/ebe7-6eah.json", "dataset_id": "ebe7-6eah"},
    "environment.beach_water_samples": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/2xir-kwzz", "api_url": "https://data.cityofnewyork.us/resource/2xir-kwzz.json", "dataset_id": "2xir-kwzz"},
    "environment.community_health_survey": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/csut-3wpr", "api_url": "https://data.cityofnewyork.us/resource/csut-3wpr.json", "dataset_id": "csut-3wpr"},
    "environment.dsny_tonnage": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ebb7-mvp5", "api_url": "https://data.cityofnewyork.us/resource/ebb7-mvp5.json", "dataset_id": "ebb7-mvp5"},
    "environment.e_designations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/hxm3-23vy", "api_url": "https://data.cityofnewyork.us/resource/hxm3-23vy.json", "dataset_id": "hxm3-23vy"},
    "environment.flood_vulnerability": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/mrjc-v9pm", "api_url": "https://data.cityofnewyork.us/resource/mrjc-v9pm.json", "dataset_id": "mrjc-v9pm"},
    "environment.heat_vulnerability": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4mhf-duep", "api_url": "https://data.cityofnewyork.us/resource/4mhf-duep.json", "dataset_id": "4mhf-duep"},
    "environment.hyperlocal_temp": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qdq3-9eqn", "api_url": "https://data.cityofnewyork.us/resource/qdq3-9eqn.json", "dataset_id": "qdq3-9eqn"},
    "environment.lead_children": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tnry-kwh5", "api_url": "https://data.cityofnewyork.us/resource/tnry-kwh5.json", "dataset_id": "tnry-kwh5"},
    "environment.lead_service_lines": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/j63k-4n92", "api_url": "https://health.data.ny.gov/resource/j63k-4n92.json", "dataset_id": "j63k-4n92"},
    "environment.ll84_energy_2023": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5zyy-y8am", "api_url": "https://data.cityofnewyork.us/resource/5zyy-y8am.json", "dataset_id": "5zyy-y8am"},
    "environment.ll84_energy_monthly": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/fvp3-gcb2", "api_url": "https://data.cityofnewyork.us/resource/fvp3-gcb2.json", "dataset_id": "fvp3-gcb2"},
    "environment.nys_solar": {"provider": "socrata", "source_url": "https://data.ny.gov/d/3x8r-34rs", "api_url": "https://data.ny.gov/resource/3x8r-34rs.json", "dataset_id": "3x8r-34rs"},
    "environment.oer_cleanup": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/3279-pp7v", "api_url": "https://data.cityofnewyork.us/resource/3279-pp7v.json", "dataset_id": "3279-pp7v"},
    "environment.recycling_rates": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/gaq9-z3hz", "api_url": "https://data.cityofnewyork.us/resource/gaq9-z3hz.json", "dataset_id": "gaq9-z3hz"},
    "environment.street_trees": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/uvpi-gqnh", "api_url": "https://data.cityofnewyork.us/resource/uvpi-gqnh.json", "dataset_id": "uvpi-gqnh"},
    "environment.waste_transfer": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ufxk-pq9j", "api_url": "https://data.cityofnewyork.us/resource/ufxk-pq9j.json", "dataset_id": "ufxk-pq9j"},
    "federal.acs_demographics": {"provider": "census", "source_url": "https://data.census.gov/table/ACSDP5Y2022.DP05"},
    "federal.acs_zcta_demographics": {"provider": "census", "source_url": "https://data.census.gov/table/ACSDP5Y2022.DP05"},
    "federal.bls_unemployment_bronx": {"provider": "bls", "source_url": "https://www.bls.gov/lau/"},
    "federal.bls_unemployment_brooklyn": {"provider": "bls", "source_url": "https://www.bls.gov/lau/"},
    "federal.bls_unemployment_manhattan": {"provider": "bls", "source_url": "https://www.bls.gov/lau/"},
    "federal.bls_unemployment_queens": {"provider": "bls", "source_url": "https://www.bls.gov/lau/"},
    "federal.bls_unemployment_staten_island": {"provider": "bls", "source_url": "https://www.bls.gov/lau/"},
    "federal.cl_financial_disclosures": {"provider": "courtlistener", "source_url": "https://www.courtlistener.com/api/rest/v4/financial-disclosures/"},
    "federal.cl_fjc_cases": {"provider": "courtlistener", "source_url": "https://www.courtlistener.com/api/rest/v4/dockets/"},
    "federal.cl_judges": {"provider": "courtlistener", "source_url": "https://www.courtlistener.com/api/rest/v4/people/"},
    "federal.cl_nypd_cases_edny": {"provider": "courtlistener", "source_url": "https://www.courtlistener.com/api/rest/v4/dockets/?court=nyed"},
    "federal.cl_nypd_cases_sdny": {"provider": "courtlistener", "source_url": "https://www.courtlistener.com/api/rest/v4/dockets/?court=nysd"},
    "federal.college_scorecard_schools": {"provider": "scorecard", "source_url": "https://api.data.gov/ed/collegescorecard/v1/schools?api_key=DEMO_KEY&per_page=1"},
    "federal.epa_echo_facilities": {"provider": "epa", "source_url": "https://echo.epa.gov/tools/data-downloads"},
    "federal.epa_echo_facilities_bronx": {"provider": "epa", "source_url": "https://echo.epa.gov/tools/data-downloads"},
    "federal.epa_echo_facilities_brooklyn": {"provider": "epa", "source_url": "https://echo.epa.gov/tools/data-downloads"},
    "federal.epa_echo_facilities_manhattan": {"provider": "epa", "source_url": "https://echo.epa.gov/tools/data-downloads"},
    "federal.epa_echo_facilities_queens": {"provider": "epa", "source_url": "https://echo.epa.gov/tools/data-downloads"},
    "federal.epa_echo_facilities_staten_island": {"provider": "epa", "source_url": "https://echo.epa.gov/tools/data-downloads"},
    "federal.fda_food_enforcement": {"provider": "fda", "source_url": "https://api.fda.gov/food/enforcement.json?limit=1"},
    "federal.fec_contributions": {"provider": "fec", "source_url": "https://api.open.fec.gov/v1/schedules/schedule_a/?per_page=1&api_key=DEMO_KEY"},
    "federal.hud_housing_choice_vouchers": {"provider": "hud", "source_url": "https://www.huduser.gov/portal/datasets/pictures.html"},
    "federal.hud_public_housing_buildings": {"provider": "hud", "source_url": "https://www.huduser.gov/portal/datasets/pis.html"},
    "federal.hud_public_housing_developments": {"provider": "hud", "source_url": "https://www.huduser.gov/portal/datasets/pis.html"},
    "federal.littlesis_entities": {"provider": "littlesis", "source_url": "https://littlesis.org/"},
    "federal.littlesis_relationships": {"provider": "littlesis", "source_url": "https://littlesis.org/"},
    "federal.name_index": {"provider": "internal"},
    "federal.name_index_raw": {"provider": "internal"},
    "federal.nrel_alt_fuel_stations": {"provider": "nrel"},
    "federal.nrel_alt_fuel_stations__ev_charging_units": {"provider": "nrel", "source_url": "https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/"},
    "federal.nrel_alt_fuel_stations__ev_connector_types": {"provider": "nrel", "source_url": "https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/"},
    "federal.nrel_alt_fuel_stations__ev_network_ids__posts": {"provider": "nrel", "source_url": "https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/"},
    "federal.nrel_alt_fuel_stations__ev_network_ids__station": {"provider": "nrel", "source_url": "https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/"},
    "federal.nypd_ccrb_complaints": {"provider": "ccrb", "source_url": "https://www.nyc.gov/site/ccrb/policy/data-transparency-initiative.page"},
    "federal.nypd_ccrb_officers_current": {"provider": "ccrb", "source_url": "https://www.nyc.gov/site/ccrb/policy/data-transparency-initiative.page"},
    "federal.nys_campaign_finance": {"provider": "nys", "source_url": "https://www.elections.ny.gov/CFViewReports.html"},
    "federal.nys_death_index": {"provider": "nys", "source_url": "https://data.ny.gov/"},
    "federal.police_settlements_538": {"provider": "static"},
    "federal.propublica_nonprofits": {"provider": "propublica", "source_url": "https://projects.propublica.org/nonprofits/"},
    "federal.resolved_entities": {"provider": "internal"},
    "federal.usaspending_contracts": {"provider": "usaspending", "source_url": "https://www.usaspending.gov/download_center/award_data_archive"},
    "federal.usaspending_grants": {"provider": "usaspending", "source_url": "https://www.usaspending.gov/download_center/award_data_archive"},
    "financial.nys_attorney_registrations": {"provider": "socrata", "source_url": "https://data.ny.gov/d/eqw2-r5nb", "api_url": "https://data.ny.gov/resource/eqw2-r5nb.json", "dataset_id": "eqw2-r5nb"},
    "financial.nys_child_support_warrants": {"provider": "socrata", "source_url": "https://data.ny.gov/d/8pp4-isha", "api_url": "https://data.ny.gov/resource/8pp4-isha.json", "dataset_id": "8pp4-isha"},
    "financial.nys_cosmetology_licenses": {"provider": "socrata", "source_url": "https://data.ny.gov/d/ucu3-8265", "api_url": "https://data.ny.gov/resource/ucu3-8265.json", "dataset_id": "ucu3-8265"},
    "financial.nys_elevator_licenses": {"provider": "socrata", "source_url": "https://data.ny.gov/d/cxfs-ya8e", "api_url": "https://data.ny.gov/resource/cxfs-ya8e.json", "dataset_id": "cxfs-ya8e"},
    "financial.nys_ida_projects": {"provider": "socrata", "source_url": "https://data.ny.gov/d/9rtk-3fkw", "api_url": "https://data.ny.gov/resource/9rtk-3fkw.json", "dataset_id": "9rtk-3fkw"},
    "financial.nys_notaries": {"provider": "socrata", "source_url": "https://data.ny.gov/d/rwbv-mz6z", "api_url": "https://data.ny.gov/resource/rwbv-mz6z.json", "dataset_id": "rwbv-mz6z"},
    "financial.nys_procurement_local": {"provider": "socrata", "source_url": "https://data.ny.gov/d/8w5p-k45m", "api_url": "https://data.ny.gov/resource/8w5p-k45m.json", "dataset_id": "8w5p-k45m"},
    "financial.nys_procurement_state": {"provider": "socrata", "source_url": "https://data.ny.gov/d/ehig-g5x3", "api_url": "https://data.ny.gov/resource/ehig-g5x3.json", "dataset_id": "ehig-g5x3"},
    "financial.nys_re_appraisers": {"provider": "socrata", "source_url": "https://data.ny.gov/d/3nr4-s9yt", "api_url": "https://data.ny.gov/resource/3nr4-s9yt.json", "dataset_id": "3nr4-s9yt"},
    "financial.nys_re_brokers": {"provider": "socrata", "source_url": "https://data.ny.gov/d/yg7h-zjbf", "api_url": "https://data.ny.gov/resource/yg7h-zjbf.json", "dataset_id": "yg7h-zjbf"},
    "financial.nys_tax_warrants": {"provider": "socrata", "source_url": "https://data.ny.gov/d/v7ua-z23v", "api_url": "https://data.ny.gov/resource/v7ua-z23v.json", "dataset_id": "v7ua-z23v"},
    "health.cdc_places": {"provider": "socrata", "source_url": "https://data.cdc.gov/d/swc5-untb", "api_url": "https://data.cdc.gov/resource/swc5-untb.json", "dataset_id": "swc5-untb"},
    "health.childcare_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dsg6-ifza", "api_url": "https://data.cityofnewyork.us/resource/dsg6-ifza.json", "dataset_id": "dsg6-ifza"},
    "health.childcare_inspections_current": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5ery-qagt", "api_url": "https://data.cityofnewyork.us/resource/5ery-qagt.json", "dataset_id": "5ery-qagt"},
    "health.childcare_programs": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/gy3q-4tzp", "api_url": "https://data.cityofnewyork.us/resource/gy3q-4tzp.json", "dataset_id": "gy3q-4tzp"},
    "health.cooling_tower_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/f9wb-g8mb", "api_url": "https://data.cityofnewyork.us/resource/f9wb-g8mb.json", "dataset_id": "f9wb-g8mb"},
    "health.covid_by_zip": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/pri4-ifjk", "api_url": "https://data.cityofnewyork.us/resource/pri4-ifjk.json", "dataset_id": "pri4-ifjk"},
    "health.covid_outcomes": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/cwmx-mvra", "api_url": "https://data.cityofnewyork.us/resource/cwmx-mvra.json", "dataset_id": "cwmx-mvra"},
    "health.drinking_water_tank_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/rytv-g5ui", "api_url": "https://data.cityofnewyork.us/resource/rytv-g5ui.json", "dataset_id": "rytv-g5ui"},
    "health.drinking_water_tanks": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/gjm4-k24g", "api_url": "https://data.cityofnewyork.us/resource/gjm4-k24g.json", "dataset_id": "gjm4-k24g"},
    "health.ed_flu_visits": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/2nwg-uqyg", "api_url": "https://data.cityofnewyork.us/resource/2nwg-uqyg.json", "dataset_id": "2nwg-uqyg"},
    "health.health_facilities": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/vn5v-hh5r", "api_url": "https://health.data.ny.gov/resource/vn5v-hh5r.json", "dataset_id": "vn5v-hh5r"},
    "health.hiv_aids_annual": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/fju2-rdad", "api_url": "https://data.cityofnewyork.us/resource/fju2-rdad.json", "dataset_id": "fju2-rdad"},
    "health.hiv_aids_by_neighborhood": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dxnu-p2qd", "api_url": "https://data.cityofnewyork.us/resource/dxnu-p2qd.json", "dataset_id": "dxnu-p2qd"},
    "health.leading_causes_of_death": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/jb7j-dtam", "api_url": "https://data.cityofnewyork.us/resource/jb7j-dtam.json", "dataset_id": "jb7j-dtam"},
    "health.medicaid_providers": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/keti-qx5t", "api_url": "https://health.data.ny.gov/resource/keti-qx5t.json", "dataset_id": "keti-qx5t"},
    "health.open_restaurant_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4dx7-axux", "api_url": "https://data.cityofnewyork.us/resource/4dx7-axux.json", "dataset_id": "4dx7-axux"},
    "health.restaurant_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/43nn-pn8j", "api_url": "https://data.cityofnewyork.us/resource/43nn-pn8j.json", "dataset_id": "43nn-pn8j"},
    "health.rodent_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/p937-wjvj", "api_url": "https://data.cityofnewyork.us/resource/p937-wjvj.json", "dataset_id": "p937-wjvj"},
    "health.school_cafeteria_inspections": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/9hxz-c2kj", "api_url": "https://data.cityofnewyork.us/resource/9hxz-c2kj.json", "dataset_id": "9hxz-c2kj"},
    "health.sparcs_discharges_2020": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/nxi5-zj9x", "api_url": "https://health.data.ny.gov/resource/nxi5-zj9x.json", "dataset_id": "nxi5-zj9x"},
    "health.sparcs_discharges_2021": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/tg3i-cinn", "api_url": "https://health.data.ny.gov/resource/tg3i-cinn.json", "dataset_id": "tg3i-cinn"},
    "health.sparcs_discharges_2022": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/5dtw-tffi", "api_url": "https://health.data.ny.gov/resource/5dtw-tffi.json", "dataset_id": "5dtw-tffi"},
    "health.sparcs_discharges_2023": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/46xm-urtu", "api_url": "https://health.data.ny.gov/resource/46xm-urtu.json", "dataset_id": "46xm-urtu"},
    "health.sparcs_discharges_2024": {"provider": "socrata", "source_url": "https://health.data.ny.gov/d/sf4k-39ay", "api_url": "https://health.data.ny.gov/resource/sf4k-39ay.json", "dataset_id": "sf4k-39ay"},
    "health.wastewater_sarscov2": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/f7dc-2q9f", "api_url": "https://data.cityofnewyork.us/resource/f7dc-2q9f.json", "dataset_id": "f7dc-2q9f"},
    "housing.acris_legals": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/8h5j-fqxa", "api_url": "https://data.cityofnewyork.us/resource/8h5j-fqxa.json", "dataset_id": "8h5j-fqxa"},
    "housing.acris_master": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bnx9-e6tj", "api_url": "https://data.cityofnewyork.us/resource/bnx9-e6tj.json", "dataset_id": "bnx9-e6tj"},
    "housing.acris_parties": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/636b-3b5g", "api_url": "https://data.cityofnewyork.us/resource/636b-3b5g.json", "dataset_id": "636b-3b5g"},
    "housing.acris_pp_legals": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/uqqa-hym2", "api_url": "https://data.cityofnewyork.us/resource/uqqa-hym2.json", "dataset_id": "uqqa-hym2"},
    "housing.acris_pp_master": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/sv7x-dduq", "api_url": "https://data.cityofnewyork.us/resource/sv7x-dduq.json", "dataset_id": "sv7x-dduq"},
    "housing.acris_pp_references": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/6y3e-jcrc", "api_url": "https://data.cityofnewyork.us/resource/6y3e-jcrc.json", "dataset_id": "6y3e-jcrc"},
    "housing.aep_buildings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/hcir-3275", "api_url": "https://data.cityofnewyork.us/resource/hcir-3275.json", "dataset_id": "hcir-3275"},
    "housing.affordable_housing": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/hg8x-zxpr", "api_url": "https://data.cityofnewyork.us/resource/hg8x-zxpr.json", "dataset_id": "hg8x-zxpr"},
    "housing.conh_pilot": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bzxi-2tsw", "api_url": "https://data.cityofnewyork.us/resource/bzxi-2tsw.json", "dataset_id": "bzxi-2tsw"},
    "housing.designated_buildings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ncre-qhxs", "api_url": "https://data.cityofnewyork.us/resource/ncre-qhxs.json", "dataset_id": "ncre-qhxs"},
    "housing.dob_application_owners": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/92ej-mfxh", "api_url": "https://data.cityofnewyork.us/resource/92ej-mfxh.json", "dataset_id": "92ej-mfxh"},
    "housing.dob_complaints": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/eabe-havv", "api_url": "https://data.cityofnewyork.us/resource/eabe-havv.json", "dataset_id": "eabe-havv"},
    "housing.dob_ecb_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/6bgk-3dad", "api_url": "https://data.cityofnewyork.us/resource/6bgk-3dad.json", "dataset_id": "6bgk-3dad"},
    "housing.dob_now_build_filings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/w9ak-ipjd", "api_url": "https://data.cityofnewyork.us/resource/w9ak-ipjd.json", "dataset_id": "w9ak-ipjd"},
    "housing.dob_permit_issuance": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ipu4-2q9a", "api_url": "https://data.cityofnewyork.us/resource/ipu4-2q9a.json", "dataset_id": "ipu4-2q9a"},
    "housing.dob_safety_boiler": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/52dp-yji6", "api_url": "https://data.cityofnewyork.us/resource/52dp-yji6.json", "dataset_id": "52dp-yji6"},
    "housing.dob_safety_facades": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xubg-57si", "api_url": "https://data.cityofnewyork.us/resource/xubg-57si.json", "dataset_id": "xubg-57si"},
    "housing.dob_safety_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/855j-jady", "api_url": "https://data.cityofnewyork.us/resource/855j-jady.json", "dataset_id": "855j-jady"},
    "housing.dob_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/3h2n-5cm9", "api_url": "https://data.cityofnewyork.us/resource/3h2n-5cm9.json", "dataset_id": "3h2n-5cm9"},
    "housing.dwelling_registrations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tesw-yqqr", "api_url": "https://data.cityofnewyork.us/resource/tesw-yqqr.json", "dataset_id": "tesw-yqqr"},
    "housing.emergency_repair_hwo": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/sbnd-xujn", "api_url": "https://data.cityofnewyork.us/resource/sbnd-xujn.json", "dataset_id": "sbnd-xujn"},
    "housing.emergency_repair_omo": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/mdbu-nrqn", "api_url": "https://data.cityofnewyork.us/resource/mdbu-nrqn.json", "dataset_id": "mdbu-nrqn"},
    "housing.evictions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/6z8x-wfk4", "api_url": "https://data.cityofnewyork.us/resource/6z8x-wfk4.json", "dataset_id": "6z8x-wfk4"},
    "housing.fdny_vacate_list": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/n5xc-7jfa", "api_url": "https://data.cityofnewyork.us/resource/n5xc-7jfa.json", "dataset_id": "n5xc-7jfa"},
    "housing.fdny_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bi53-yph3", "api_url": "https://data.cityofnewyork.us/resource/bi53-yph3.json", "dataset_id": "bi53-yph3"},
    "housing.housing_connect_buildings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/nibs-na6y", "api_url": "https://data.cityofnewyork.us/resource/nibs-na6y.json", "dataset_id": "nibs-na6y"},
    "housing.housing_connect_lotteries": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/vy5i-a666", "api_url": "https://data.cityofnewyork.us/resource/vy5i-a666.json", "dataset_id": "vy5i-a666"},
    "housing.hpd_complaints": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ygpa-z7cr", "api_url": "https://data.cityofnewyork.us/resource/ygpa-z7cr.json", "dataset_id": "ygpa-z7cr"},
    "housing.hpd_jurisdiction": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/kj4p-ruqc", "api_url": "https://data.cityofnewyork.us/resource/kj4p-ruqc.json", "dataset_id": "kj4p-ruqc"},
    "housing.hpd_litigations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/59kj-x8nc", "api_url": "https://data.cityofnewyork.us/resource/59kj-x8nc.json", "dataset_id": "59kj-x8nc"},
    "housing.hpd_registration_contacts": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/feu5-w2e2", "api_url": "https://data.cityofnewyork.us/resource/feu5-w2e2.json", "dataset_id": "feu5-w2e2"},
    "housing.hpd_repair_vacate": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tb8q-a3ar", "api_url": "https://data.cityofnewyork.us/resource/tb8q-a3ar.json", "dataset_id": "tb8q-a3ar"},
    "housing.hpd_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/wvxf-dwi5", "api_url": "https://data.cityofnewyork.us/resource/wvxf-dwi5.json", "dataset_id": "wvxf-dwi5"},
    "housing.j51_historical": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/y7az-s7wc", "api_url": "https://data.cityofnewyork.us/resource/y7az-s7wc.json", "dataset_id": "y7az-s7wc"},
    "housing.ll44_income_rent": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/9ay9-xkek", "api_url": "https://data.cityofnewyork.us/resource/9ay9-xkek.json", "dataset_id": "9ay9-xkek"},
    "housing.nyc_water_charges": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/a3bk-efmk", "api_url": "https://data.cityofnewyork.us/resource/a3bk-efmk.json", "dataset_id": "a3bk-efmk"},
    "housing.oca_addresses": {"provider": "oca", "source_url": "https://iapps.courts.state.ny.us/nyscef"},
    "housing.oca_causes": {"provider": "oca", "source_url": "https://iapps.courts.state.ny.us/nyscef"},
    "housing.oca_index": {"provider": "oca", "source_url": "https://iapps.courts.state.ny.us/nyscef"},
    "housing.oca_parties": {"provider": "oca", "source_url": "https://iapps.courts.state.ny.us/nyscef"},
    "housing.pad_crosswalk": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bc8t-ecyu", "api_url": "https://data.cityofnewyork.us/resource/bc8t-ecyu.json", "dataset_id": "bc8t-ecyu"},
    "housing.property_abatement_detail": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/rgyu-ii48", "api_url": "https://data.cityofnewyork.us/resource/rgyu-ii48.json", "dataset_id": "rgyu-ii48"},
    "housing.property_assessment": {"provider": "socrata", "source_url": "https://data.ny.gov/d/iq85-sdzs", "api_url": "https://data.ny.gov/resource/iq85-sdzs.json", "dataset_id": "iq85-sdzs"},
    "housing.property_charges": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/scjx-j6np", "api_url": "https://data.cityofnewyork.us/resource/scjx-j6np.json", "dataset_id": "scjx-j6np"},
    "housing.property_valuation": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/8y4t-faws", "api_url": "https://data.cityofnewyork.us/resource/8y4t-faws.json", "dataset_id": "8y4t-faws"},
    "housing.rolling_sales": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/usep-8jbt", "api_url": "https://data.cityofnewyork.us/resource/usep-8jbt.json", "dataset_id": "usep-8jbt"},
    "housing.rpie_noncompliance": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/wvts-6tdf", "api_url": "https://data.cityofnewyork.us/resource/wvts-6tdf.json", "dataset_id": "wvts-6tdf"},
    "housing.sro_buildings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/cmak-ujff", "api_url": "https://data.cityofnewyork.us/resource/cmak-ujff.json", "dataset_id": "cmak-ujff"},
    "housing.tax_exemptions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/muvi-b6kx", "api_url": "https://data.cityofnewyork.us/resource/muvi-b6kx.json", "dataset_id": "muvi-b6kx"},
    "housing.tax_lien_sales": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/9rz4-mjek", "api_url": "https://data.cityofnewyork.us/resource/9rz4-mjek.json", "dataset_id": "9rz4-mjek"},
    "housing.underlying_conditions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xpbf-ithr", "api_url": "https://data.cityofnewyork.us/resource/xpbf-ithr.json", "dataset_id": "xpbf-ithr"},
    "housing.vacate_relocation": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/3bkg-usya", "api_url": "https://data.cityofnewyork.us/resource/3bkg-usya.json", "dataset_id": "3bkg-usya"},
    "public_safety.ccrb_allegations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/6xgr-kwjq", "api_url": "https://data.cityofnewyork.us/resource/6xgr-kwjq.json", "dataset_id": "6xgr-kwjq"},
    "public_safety.ccrb_complaints": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/2mby-ccnw", "api_url": "https://data.cityofnewyork.us/resource/2mby-ccnw.json", "dataset_id": "2mby-ccnw"},
    "public_safety.ccrb_officers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/2fir-qns4", "api_url": "https://data.cityofnewyork.us/resource/2fir-qns4.json", "dataset_id": "2fir-qns4"},
    "public_safety.ccrb_penalties": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/keep-pkmh", "api_url": "https://data.cityofnewyork.us/resource/keep-pkmh.json", "dataset_id": "keep-pkmh"},
    "public_safety.criminal_court_summons": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/sv2w-rv3k", "api_url": "https://data.cityofnewyork.us/resource/sv2w-rv3k.json", "dataset_id": "sv2w-rv3k"},
    "public_safety.daily_inmates": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/7479-ugqb", "api_url": "https://data.cityofnewyork.us/resource/7479-ugqb.json", "dataset_id": "7479-ugqb"},
    "public_safety.discipline_charges": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/uafj-ik29", "api_url": "https://data.cityofnewyork.us/resource/uafj-ik29.json", "dataset_id": "uafj-ik29"},
    "public_safety.discipline_summary": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/wq9a-qu9a", "api_url": "https://data.cityofnewyork.us/resource/wq9a-qu9a.json", "dataset_id": "wq9a-qu9a"},
    "public_safety.hate_crimes": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bqiq-cu78", "api_url": "https://data.cityofnewyork.us/resource/bqiq-cu78.json", "dataset_id": "bqiq-cu78"},
    "public_safety.motor_vehicle_collisions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/h9gi-nx95", "api_url": "https://data.cityofnewyork.us/resource/h9gi-nx95.json", "dataset_id": "h9gi-nx95"},
    "public_safety.nyc_claims_report": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ex6k-ym48", "api_url": "https://data.cityofnewyork.us/resource/ex6k-ym48.json", "dataset_id": "ex6k-ym48"},
    "public_safety.nypd_arrests_historic": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/8h9b-rp9u", "api_url": "https://data.cityofnewyork.us/resource/8h9b-rp9u.json", "dataset_id": "8h9b-rp9u"},
    "public_safety.nypd_arrests_ytd": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/uip8-fykc", "api_url": "https://data.cityofnewyork.us/resource/uip8-fykc.json", "dataset_id": "uip8-fykc"},
    "public_safety.nypd_complaints_historic": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qgea-i56i", "api_url": "https://data.cityofnewyork.us/resource/qgea-i56i.json", "dataset_id": "qgea-i56i"},
    "public_safety.nypd_complaints_ytd": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5uac-w243", "api_url": "https://data.cityofnewyork.us/resource/5uac-w243.json", "dataset_id": "5uac-w243"},
    "public_safety.nypd_officer_profile": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/pmsy-ewrc", "api_url": "https://data.cityofnewyork.us/resource/pmsy-ewrc.json", "dataset_id": "pmsy-ewrc"},
    "public_safety.nys_crash_vehicles": {"provider": "socrata", "source_url": "https://data.ny.gov/d/xe9x-a24f", "api_url": "https://data.ny.gov/resource/xe9x-a24f.json", "dataset_id": "xe9x-a24f"},
    "public_safety.nys_crashes": {"provider": "socrata", "source_url": "https://data.ny.gov/d/e8ky-4vqe", "api_url": "https://data.ny.gov/resource/e8ky-4vqe.json", "dataset_id": "e8ky-4vqe"},
    "public_safety.shootings": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5ucz-vwe8", "api_url": "https://data.cityofnewyork.us/resource/5ucz-vwe8.json", "dataset_id": "5ucz-vwe8"},
    "public_safety.use_of_force_incidents": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/f4tj-796d", "api_url": "https://data.cityofnewyork.us/resource/f4tj-796d.json", "dataset_id": "f4tj-796d"},
    "public_safety.use_of_force_officers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/v5jd-6wqn", "api_url": "https://data.cityofnewyork.us/resource/v5jd-6wqn.json", "dataset_id": "v5jd-6wqn"},
    "public_safety.use_of_force_subjects": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dufe-vxb7", "api_url": "https://data.cityofnewyork.us/resource/dufe-vxb7.json", "dataset_id": "dufe-vxb7"},
    "recreation.active_passive_rec": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/kcqe-vnci", "api_url": "https://data.cityofnewyork.us/resource/kcqe-vnci.json", "dataset_id": "kcqe-vnci"},
    "recreation.aquatics": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/bzby-7sfr", "api_url": "https://data.cityofnewyork.us/resource/bzby-7sfr.json", "dataset_id": "bzby-7sfr"},
    "recreation.baby_names": {"provider": "static"},
    "recreation.canine_waste": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/5npv-j6gn", "api_url": "https://data.cityofnewyork.us/resource/5npv-j6gn.json", "dataset_id": "5npv-j6gn"},
    "recreation.capital_projects": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4hcv-tc5r", "api_url": "https://data.cityofnewyork.us/resource/4hcv-tc5r.json", "dataset_id": "4hcv-tc5r"},
    "recreation.drinking_fountains": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qnv7-p7a2", "api_url": "https://data.cityofnewyork.us/resource/qnv7-p7a2.json", "dataset_id": "qnv7-p7a2"},
    "recreation.fishing_sites": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/mvte-j9h9", "api_url": "https://data.cityofnewyork.us/resource/mvte-j9h9.json", "dataset_id": "mvte-j9h9"},
    "recreation.functional_parkland": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xhvt-s4va", "api_url": "https://data.cityofnewyork.us/resource/xhvt-s4va.json", "dataset_id": "xhvt-s4va"},
    "recreation.lap_swimming": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4cga-5i5v", "api_url": "https://data.cityofnewyork.us/resource/4cga-5i5v.json", "dataset_id": "4cga-5i5v"},
    "recreation.nys_farmers_markets": {"provider": "socrata", "source_url": "https://data.ny.gov/d/qq4h-8p86", "api_url": "https://data.ny.gov/resource/qq4h-8p86.json", "dataset_id": "qq4h-8p86"},
    "recreation.permit_areas": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/c5vm-g2dk", "api_url": "https://data.cityofnewyork.us/resource/c5vm-g2dk.json", "dataset_id": "c5vm-g2dk"},
    "recreation.play_areas": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/j55h-3upk", "api_url": "https://data.cityofnewyork.us/resource/j55h-3upk.json", "dataset_id": "j55h-3upk"},
    "recreation.pool_sessions": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/82jf-bykm", "api_url": "https://data.cityofnewyork.us/resource/82jf-bykm.json", "dataset_id": "82jf-bykm"},
    "recreation.pools": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/y5rm-wagw", "api_url": "https://data.cityofnewyork.us/resource/y5rm-wagw.json", "dataset_id": "y5rm-wagw"},
    "recreation.properties": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/enfh-gkve", "api_url": "https://data.cityofnewyork.us/resource/enfh-gkve.json", "dataset_id": "enfh-gkve"},
    "recreation.restrictive_declarations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/cmni-fvnx", "api_url": "https://data.cityofnewyork.us/resource/cmni-fvnx.json", "dataset_id": "cmni-fvnx"},
    "recreation.signs": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/hv9n-xgy4", "api_url": "https://data.cityofnewyork.us/resource/hv9n-xgy4.json", "dataset_id": "hv9n-xgy4"},
    "recreation.special_events": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/6v4b-5gp4", "api_url": "https://data.cityofnewyork.us/resource/6v4b-5gp4.json", "dataset_id": "6v4b-5gp4"},
    "recreation.spray_showers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ckaz-6gaa", "api_url": "https://data.cityofnewyork.us/resource/ckaz-6gaa.json", "dataset_id": "ckaz-6gaa"},
    "recreation.summer_sports_2017": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xeg4-ic28", "api_url": "https://data.cityofnewyork.us/resource/xeg4-ic28.json", "dataset_id": "xeg4-ic28"},
    "recreation.summer_sports_2022": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4pta-f4ca", "api_url": "https://data.cityofnewyork.us/resource/4pta-f4ca.json", "dataset_id": "4pta-f4ca"},
    "recreation.synthetic_turf": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/weh8-3ujf", "api_url": "https://data.cityofnewyork.us/resource/weh8-3ujf.json", "dataset_id": "weh8-3ujf"},
    "recreation.turf_maintenance": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tja3-yjvi", "api_url": "https://data.cityofnewyork.us/resource/tja3-yjvi.json", "dataset_id": "tja3-yjvi"},
    "recreation.turf_sites": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/7qsb-ehm7", "api_url": "https://data.cityofnewyork.us/resource/7qsb-ehm7.json", "dataset_id": "7qsb-ehm7"},
    "recreation.waterfront": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/jr73-mxkz", "api_url": "https://data.cityofnewyork.us/resource/jr73-mxkz.json", "dataset_id": "jr73-mxkz"},
    "recreation.waterfront_access": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/388s-pnvc", "api_url": "https://data.cityofnewyork.us/resource/388s-pnvc.json", "dataset_id": "388s-pnvc"},
    "social_services.access_nyc": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/kvhd-5fmu", "api_url": "https://data.cityofnewyork.us/resource/kvhd-5fmu.json", "dataset_id": "kvhd-5fmu"},
    "social_services.benefits_centers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/9d9t-bmk7", "api_url": "https://data.cityofnewyork.us/resource/9d9t-bmk7.json", "dataset_id": "9d9t-bmk7"},
    "social_services.broadband_adoption": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/qz5f-yx82", "api_url": "https://data.cityofnewyork.us/resource/qz5f-yx82.json", "dataset_id": "qz5f-yx82"},
    "social_services.community_gardens": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/p78i-pat6", "api_url": "https://data.cityofnewyork.us/resource/p78i-pat6.json", "dataset_id": "p78i-pat6"},
    "social_services.community_orgs": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/i4kb-6ab6", "api_url": "https://data.cityofnewyork.us/resource/i4kb-6ab6.json", "dataset_id": "i4kb-6ab6"},
    "social_services.dhs_daily_report": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/k46n-sa2m", "api_url": "https://data.cityofnewyork.us/resource/k46n-sa2m.json", "dataset_id": "k46n-sa2m"},
    "social_services.dhs_shelter_census": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/3pjg-ncn9", "api_url": "https://data.cityofnewyork.us/resource/3pjg-ncn9.json", "dataset_id": "3pjg-ncn9"},
    "social_services.dycd_program_sites": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ebkm-iyma", "api_url": "https://data.cityofnewyork.us/resource/ebkm-iyma.json", "dataset_id": "ebkm-iyma"},
    "social_services.equity_nyc": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/8ek7-jxw6", "api_url": "https://data.cityofnewyork.us/resource/8ek7-jxw6.json", "dataset_id": "8ek7-jxw6"},
    "social_services.family_justice_centers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/xggi-kgx9", "api_url": "https://data.cityofnewyork.us/resource/xggi-kgx9.json", "dataset_id": "xggi-kgx9"},
    "social_services.farmers_markets": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/8vwk-6iz2", "api_url": "https://data.cityofnewyork.us/resource/8vwk-6iz2.json", "dataset_id": "8vwk-6iz2"},
    "social_services.idnyc_applications": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/rtmc-bhid", "api_url": "https://data.cityofnewyork.us/resource/rtmc-bhid.json", "dataset_id": "rtmc-bhid"},
    "social_services.know_your_rights": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/pnpe-ubtz", "api_url": "https://data.cityofnewyork.us/resource/pnpe-ubtz.json", "dataset_id": "pnpe-ubtz"},
    "social_services.language_secret_shopper": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/3m3d-zzwn", "api_url": "https://data.cityofnewyork.us/resource/3m3d-zzwn.json", "dataset_id": "3m3d-zzwn"},
    "social_services.lep_population": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ajin-gkbp", "api_url": "https://data.cityofnewyork.us/resource/ajin-gkbp.json", "dataset_id": "ajin-gkbp"},
    "social_services.literacy_programs": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/h2pf-4vz5", "api_url": "https://data.cityofnewyork.us/resource/h2pf-4vz5.json", "dataset_id": "h2pf-4vz5"},
    "social_services.moia_interpretation": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/mcti-yg8i", "api_url": "https://data.cityofnewyork.us/resource/mcti-yg8i.json", "dataset_id": "mcti-yg8i"},
    "social_services.n311_interpreter_wait": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/dzvt-6g3v", "api_url": "https://data.cityofnewyork.us/resource/dzvt-6g3v.json", "dataset_id": "dzvt-6g3v"},
    "social_services.n311_service_requests": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/erm2-nwe9", "api_url": "https://data.cityofnewyork.us/resource/erm2-nwe9.json", "dataset_id": "erm2-nwe9"},
    "social_services.nys_child_care": {"provider": "socrata", "source_url": "https://data.ny.gov/d/cb42-qumz", "api_url": "https://data.ny.gov/resource/cb42-qumz.json", "dataset_id": "cb42-qumz"},
    "social_services.pregnancy_mortality": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/27x4-cbi6", "api_url": "https://data.cityofnewyork.us/resource/27x4-cbi6.json", "dataset_id": "27x4-cbi6"},
    "social_services.shop_healthy": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ud4g-9x9z", "api_url": "https://data.cityofnewyork.us/resource/ud4g-9x9z.json", "dataset_id": "ud4g-9x9z"},
    "social_services.snap_access_index": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/4c8i-cnte", "api_url": "https://data.cityofnewyork.us/resource/4c8i-cnte.json", "dataset_id": "4c8i-cnte"},
    "social_services.snap_centers": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tc6u-8rnp", "api_url": "https://data.cityofnewyork.us/resource/tc6u-8rnp.json", "dataset_id": "tc6u-8rnp"},
    "transportation.ferry_ridership": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/t5n6-gx8c", "api_url": "https://data.cityofnewyork.us/resource/t5n6-gx8c.json", "dataset_id": "t5n6-gx8c"},
    "transportation.mta_daily_ridership": {"provider": "socrata", "source_url": "https://data.ny.gov/d/vxuj-8kew", "api_url": "https://data.ny.gov/resource/vxuj-8kew.json", "dataset_id": "vxuj-8kew"},
    "transportation.mta_elevator": {"provider": "socrata", "source_url": "https://data.ny.gov/d/rc78-7x78", "api_url": "https://data.ny.gov/resource/rc78-7x78.json", "dataset_id": "rc78-7x78"},
    "transportation.mta_entrances": {"provider": "socrata", "source_url": "https://data.ny.gov/d/i9wp-a4ja", "api_url": "https://data.ny.gov/resource/i9wp-a4ja.json", "dataset_id": "i9wp-a4ja"},
    "transportation.mta_incidents": {"provider": "socrata", "source_url": "https://data.ny.gov/d/j6d2-s8m2", "api_url": "https://data.ny.gov/resource/j6d2-s8m2.json", "dataset_id": "j6d2-s8m2"},
    "transportation.mta_paratransit_max": {"provider": "socrata", "source_url": "https://data.ny.gov/d/3te2-xtd4", "api_url": "https://data.ny.gov/resource/3te2-xtd4.json", "dataset_id": "3te2-xtd4"},
    "transportation.mta_paratransit_ride": {"provider": "socrata", "source_url": "https://data.ny.gov/d/wtm4-vjm7", "api_url": "https://data.ny.gov/resource/wtm4-vjm7.json", "dataset_id": "wtm4-vjm7"},
    "transportation.mta_paratransit_ridership": {"provider": "socrata", "source_url": "https://data.ny.gov/d/fn46-66ir", "api_url": "https://data.ny.gov/resource/fn46-66ir.json", "dataset_id": "fn46-66ir"},
    "transportation.mta_stations": {"provider": "socrata", "source_url": "https://data.ny.gov/d/4ta5-wz5s", "api_url": "https://data.ny.gov/resource/4ta5-wz5s.json", "dataset_id": "4ta5-wz5s"},
    "transportation.nys_bridge_conditions": {"provider": "socrata", "source_url": "https://data.ny.gov/d/wpyb-cjy8", "api_url": "https://data.ny.gov/resource/wpyb-cjy8.json", "dataset_id": "wpyb-cjy8"},
    "transportation.nys_vehicle_registrations": {"provider": "socrata", "source_url": "https://data.ny.gov/d/w4pv-hbkt", "api_url": "https://data.ny.gov/resource/w4pv-hbkt.json", "dataset_id": "w4pv-hbkt"},
    "transportation.parking_violations": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/pvqr-7yc4", "api_url": "https://data.cityofnewyork.us/resource/pvqr-7yc4.json", "dataset_id": "pvqr-7yc4"},
    "transportation.pavement_rating": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/6yyb-pb25", "api_url": "https://data.cityofnewyork.us/resource/6yyb-pb25.json", "dataset_id": "6yyb-pb25"},
    "transportation.pedestrian_ramps": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/ufzp-rrqu", "api_url": "https://data.cityofnewyork.us/resource/ufzp-rrqu.json", "dataset_id": "ufzp-rrqu"},
    "transportation.pothole_orders": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/x9wy-ing4", "api_url": "https://data.cityofnewyork.us/resource/x9wy-ing4.json", "dataset_id": "x9wy-ing4"},
    "transportation.street_permits": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/tqtj-sjs8", "api_url": "https://data.cityofnewyork.us/resource/tqtj-sjs8.json", "dataset_id": "tqtj-sjs8"},
    "transportation.traffic_volume": {"provider": "socrata", "source_url": "https://data.cityofnewyork.us/d/7ym2-wayt", "api_url": "https://data.cityofnewyork.us/resource/7ym2-wayt.json", "dataset_id": "7ym2-wayt"},
}
